import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main>{children}</main>

        <Script strategy="beforeInteractive" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCPYtl2Sw7lGDd0zX6EInnOTXzm8PFvcmk&libraries=places" />
      </body>
    </html>
  );
}
